- name: Test of performent Phonebook-app
  hosts: preprod
  gather_facts: true
  become: true

  pre_tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*

    - name: Copy file planTest.jmx
      template:
        src: roles/phonerole/templates/planTest.j2
        dest: "{{ house }}/planTest.jmx"
        owner: centos
        remote_src: no

    - name: Copy file file.jtl
      copy:
        src: roles/phonerole/templates/file.jtl
        dest: "{{ house }}"
        owner: centos
        remote_src: no

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

  tasks:
    - name: Download apache-jmeter-5.3
      get_url:
        url: http://www.gtlib.gatech.edu/pub/apache//jmeter/binaries/apache-jmeter-5.3.tgz
        dest: /home/centos

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/centos/apache-jmeter-5.3.tgz
        dest: /home/centos
        remote_src: yes

    - name: Run a command shell
      shell: apache-jmeter-5.3/bin/jmeter.sh -n -t /home/centos/planTest.jmx -l /home/centos/file.jtl
      args:
        warn: no
